language: cpp

os: freebsd

compiler:
  - clang++
  - g++

script:
  - find src/ tests/ -regex '.*\.\(cpp\|hpp\|h\)' -exec clang-format -style=file -i {} \; && git diff --exit-code
  - mkdir build
  - cd build && cmake .. && make